<a href="https://colab.research.google.com/github/hug627/streamlit-for-30-days/blob/main/datapreprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
upload = files.upload

In [2]:
# Load the dataset, display the ten first lines, store the results in a variable called 'client_0_bills'.
import pandas as pd
client_0_bills = pd.read_csv(r'/content/STEG_BILLING_HISTORY.csv')
client_0_bills.head(10)

/tmp/ipython-input-2296680375.py:3: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  client_0_bills = pd.read_csv(r'/content/STEG_BILLING_HISTORY.csv')

,client_id,invoice_date,tarif_type,counter_number,counter_statue,counter_code,reading_remarque,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number,counter_type
0,train_Client_0,2014-03-24,11,1335667.0,0,203,8.0,1,82,0,0,0,14302,14384,4,ELEC
1,train_Client_0,2013-03-29,11,1335667.0,0,203,6.0,1,1200,184,0,0,12294,13678,4,ELEC
2,train_Client_0,2015-03-23,11,1335667.0,0,203,8.0,1,123,0,0,0,14624,14747,4,ELEC
3,train_Client_0,2015-07-13,11,1335667.0,0,207,8.0,1,102,0,0,0,14747,14849,4,ELEC
4,train_Client_0,2016-11-17,11,1335667.0,0,207,9.0,1,572,0,0,0,15066,15638,12,ELEC
5,train_Client_0,2017-07-17,11,1335667.0,0,207,9.0,1,314,0,0,0,15638,15952,8,ELEC
6,train_Client_0,2018-12-07,11,1335667.0,0,207,9.0,1,541,0,0,0,15952,16493,12,ELEC
7,train_Client_0,2019-03-19,11,1335667.0,0,207,9.0,1,585,0,0,0,16493,17078,8,ELEC
8,train_Client_0,2011-07-22,11,1335667.0,0,203,9.0,1,1200,186,0,0,7770,9156,4,ELEC
9,train_Client_0,2011-11-22,11,1335667.0,0,203,6.0,1,1082,0,0,0,9156,10238,4,ELEC

In [3]:
# What is the data type of the 'client_0_bills' variable
type(client_0_bills)

pandas.core.frame.DataFrame

In [4]:
# Display the general information of the dataset and try to answer the following questions :
# How many rows and columns do we have in this dataset ?
# How many categorical features are present in the dataset ?
# How much memory space does the dataset consume ?
client_0_bills.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4476749 entries, 0 to 4476748
Data columns (total 16 columns):
 #   Column                Dtype
---  ------                -----
 0   client_id             object
 1   invoice_date          object
 2   tarif_type            int64
 3   counter_number        float64
 4   counter_statue        object
 5   counter_code          int64
 6   reading_remarque      float64
 7   counter_coefficient   int64
 8   consommation_level_1  int64
 9   consommation_level_2  int64
 10  consommation_level_3  int64
 11  consommation_level_4  int64
 12  old_index             int64
 13  new_index             int64
 14  months_number         int64
 15  counter_type          object
dtypes: float64(2), int64(10), object(4)
memory usage: 546.5+ MB

In [5]:
# Inspect the dataset for potential missing values.
client_0_bills.isnull().sum()

client_id                  0
invoice_date               0
tarif_type                 0
counter_number            48
counter_statue             0
counter_code               0
reading_remarque        4531
counter_coefficient        0
consommation_level_1       0
consommation_level_2       0
consommation_level_3       0
consommation_level_4       0
old_index                  0
new_index                  0
months_number              0
counter_type               0
dtype: int64

In [6]:
# Select your strategy to handle missing values, and tell us why you had made that choice.

In [8]:
# Run a descriptive analysis on numeric features (columns).
# the mean on numeric features the columns
client_0_bills.describe()

,tarif_type,counter_number,counter_code,reading_remarque,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number
count,4.476749e+06,4.476701e+06,4.476749e+06,4.472218e+06,4.476749e+06,4.476749e+06,4.476749e+06,4.476749e+06,4.476749e+06,4.476749e+06,4.476749e+06,4.476749e+06
mean,2.012804e+01,1.230595e+11,1.724884e+02,7.321713e+00,1.003040e+00,4.109795e+02,1.093225e+02,2.030620e+01,5.292588e+01,1.776700e+04,1.834970e+04,4.483095e+01
std,1.347256e+01,1.657276e+12,1.338871e+02,1.571859e+00,3.083466e-01,7.573080e+02,1.220123e+03,1.574239e+02,8.754725e+02,4.036693e+04,4.095321e+04,3.128335e+03
min,8.000000e+00,0.000000e+00,0.000000e+00,5.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,1.100000e+01,1.211080e+05,5.000000e+00,6.000000e+00,1.000000e+00,7.900000e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.791000e+03,2.056000e+03,4.000000e+00
50%,1.100000e+01,4.945610e+05,2.030000e+02,8.000000e+00,1.000000e+00,2.740000e+02,0.000000e+00,0.000000e+00,0.000000e+00,7.690000e+03,8.192000e+03,4.000000e+00
75%,4.000000e+01,1.115161e+06,2.070000e+02,9.000000e+00,1.000000e+00,6.000000e+02,0.000000e+00,0.000000e+00,0.000000e+00,2.166000e+04,2.234300e+04,4.000000e+00
max,4.500000e+01,2.798115e+13,6.000000e+02,4.130000e+02,5.000000e+01,9.999100e+05,9.990730e+05,6.449200e+04,5.479460e+05,2.800280e+06,2.870972e+06,6.366240e+05

,tarif_type,counter_number,counter_code,reading_remarque,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number
count,4.476749e+06,4.476701e+06,4.476749e+06,4.472218e+06,4.476749e+06,4.476749e+06,4.476749e+06,4.476749e+06,4.476749e+06,4.476749e+06,4.476749e+06,4.476749e+06
mean,2.012804e+01,1.230595e+11,1.724884e+02,7.321713e+00,1.003040e+00,4.109795e+02,1.093225e+02,2.030620e+01,5.292588e+01,1.776700e+04,1.834970e+04,4.483095e+01
std,1.347256e+01,1.657276e+12,1.338871e+02,1.571859e+00,3.083466e-01,7.573080e+02,1.220123e+03,1.574239e+02,8.754725e+02,4.036693e+04,4.095321e+04,3.128335e+03
min,8.000000e+00,0.000000e+00,0.000000e+00,5.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,1.100000e+01,1.211080e+05,5.000000e+00,6.000000e+00,1.000000e+00,7.900000e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.791000e+03,2.056000e+03,4.000000e+00
50%,1.100000e+01,4.945610e+05,2.030000e+02,8.000000e+00,1.000000e+00,2.740000e+02,0.000000e+00,0.000000e+00,0.000000e+00,7.690000e+03,8.192000e+03,4.000000e+00
75%,4.000000e+01,1.115161e+06,2.070000e+02,9.000000e+00,1.000000e+00,6.000000e+02,0.000000e+00,0.000000e+00,0.000000e+00,2.166000e+04,2.234300e+04,4.000000e+00
max,4.500000e+01,2.798115e+13,6.000000e+02,4.130000e+02,5.000000e+01,9.999100e+05,9.990730e+05,6.449200e+04,5.479460e+05,2.800280e+06,2.870972e+06,6.366240e+05

In [14]:
# Select the bills records for the client with an id ='train_Client_0', using 2 methods.
# select client with id = 'train_Client_0
client_0_bills[client_0_bills['client_id'] == 'train_Client_0']
# another method to select client  with an id ='train_Client_0'
client_0_bills.query("client_id == 'train_Client_0'")

,client_id,invoice_date,tarif_type,counter_number,counter_statue,counter_code,reading_remarque,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number,counter_type
0,train_Client_0,2014-03-24,11,1335667.0,0,203,8.0,1,82,0,0,0,14302,14384,4,ELEC
1,train_Client_0,2013-03-29,11,1335667.0,0,203,6.0,1,1200,184,0,0,12294,13678,4,ELEC
2,train_Client_0,2015-03-23,11,1335667.0,0,203,8.0,1,123,0,0,0,14624,14747,4,ELEC
3,train_Client_0,2015-07-13,11,1335667.0,0,207,8.0,1,102,0,0,0,14747,14849,4,ELEC
4,train_Client_0,2016-11-17,11,1335667.0,0,207,9.0,1,572,0,0,0,15066,15638,12,ELEC
5,train_Client_0,2017-07-17,11,1335667.0,0,207,9.0,1,314,0,0,0,15638,15952,8,ELEC
6,train_Client_0,2018-12-07,11,1335667.0,0,207,9.0,1,541,0,0,0,15952,16493,12,ELEC
7,train_Client_0,2019-03-19,11,1335667.0,0,207,9.0,1,585,0,0,0,16493,17078,8,ELEC
8,train_Client_0,2011-07-22,11,1335667.0,0,203,9.0,1,1200,186,0,0,7770,9156,4,ELEC
9,train_Client_0,2011-11-22,11,1335667.0,0,203,6.0,1,1082,0,0,0,9156,10238,4,ELEC
10,train_Client_0,2008-11-25,11,1335667.0,0,203,6.0,1,174,0,0,0,5417,5591,4,ELEC
11,train_Client_0,2012-07-23,11,1335667.0,0,203,6.0,1,628,0,0,0,10780,11408,4,ELEC
12,train_Client_0,2012-11-29,11,1335667.0,0,203,6.0,1,886,0,0,0,11408,12294,4,ELEC
13,train_Client_0,2013-07-22,11,1335667.0,0,203,8.0,1,147,0,0,0,13983,14130,4,ELEC
14,train_Client_0,2014-07-18,11,1335667.0,0,203,8.0,1,99,0,0,0,14384,14483,4,ELEC
15,train_Client_0,2014-11-24,11,1335667.0,0,203,8.0,1,141,0,0,0,14483,14624,4,ELEC
16,train_Client_0,2015-11-18,11,1335667.0,0,207,9.0,1,217,0,0,0,14849,15066,4,ELEC
17,train_Client_0,2012-03-27,11,1335667.0,0,203,8.0,1,292,0,0,0,10488,10780,4,ELEC
18,train_Client_0,2011-03-30,11,1335667.0,0,203,6.0,1,497,0,0,0,7273,7770,4,ELEC
19,train_Client_0,2013-02-12,11,1335667.0,0,203,8.0,1,38,0,0,0,14264,14302,2,ELEC
20,train_Client_0,2010-07-22,11,1335667.0,0,203,6.0,1,278,0,0,0,6761,7039,4,ELEC
21,train_Client_0,2010-11-24,11,1335667.0,0,203,6.0,1,234,0,0,0,7039,7273,4,ELEC
22,train_Client_0,2005-10-17,11,1335667.0,0,203,6.0,1,124,0,0,0,3685,3809,4,ELEC
23,train_Client_0,2006-02-24,11,1335667.0,0,203,6.0,1,141,0,0,0,3809,3950,4,ELEC
24,train_Client_0,2006-06-23,11,1335667.0,0,203,6.0,1,162,0,0,0,3950,4112,4,ELEC
25,train_Client_0,2006-10-18,11,1335667.0,0,203,6.0,1,159,0,0,0,4112,4271,4,ELEC
26,train_Client_0,2007-06-27,11,1335667.0,0,203,6.0,1,240,0,0,0,4453,4693,4,ELEC
27,train_Client_0,2007-10-25,11,1335667.0,0,203,6.0,1,276,0,0,0,4693,4969,4,ELEC
28,train_Client_0,2007-02-26,11,1335667.0,0,203,6.0,1,182,0,0,0,4271,4453,4,ELEC
29,train_Client_0,2008-07-28,11,1335667.0,0,203,6.0,1,171,0,0,0,5246,5417,4,ELEC
30,train_Client_0,2009-01-04,11,1335667.0,0,203,6.0,1,315,0,0,0,5591,5906,4,ELEC
31,train_Client_0,2009-07-27,11,1335667.0,0,203,6.0,1,312,0,0,0,5906,6218,4,ELEC
32,train_Client_0,2009-11-24,11,1335667.0,0,203,6.0,1,267,0,0,0,6218,6485,4,ELEC
33,train_Client_0,2010-03-29,11,1335667.0,0,203,6.0,1,276,0,0,0,6485,6761,4,ELEC
34,train_Client_0,2008-01-04,11,1335667.0,0,203,6.0,1,277,0,0,0,4969,5246,4,ELEC

In [15]:
# Transform the 'counter_type' feature to a numeric variable using the encoder of your choice.
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
client_0_bills['counter_type'] = le.fit_transform(client_0_bills['counter_type'])
client_0_bills.head()

,client_id,invoice_date,tarif_type,counter_number,counter_statue,counter_code,reading_remarque,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number,counter_type
0,train_Client_0,2014-03-24,11,1335667.0,0,203,8.0,1,82,0,0,0,14302,14384,4,0
1,train_Client_0,2013-03-29,11,1335667.0,0,203,6.0,1,1200,184,0,0,12294,13678,4,0
2,train_Client_0,2015-03-23,11,1335667.0,0,203,8.0,1,123,0,0,0,14624,14747,4,0
3,train_Client_0,2015-07-13,11,1335667.0,0,207,8.0,1,102,0,0,0,14747,14849,4,0
4,train_Client_0,2016-11-17,11,1335667.0,0,207,9.0,1,572,0,0,0,15066,15638,12,0

In [16]:
# Delete the 'counter_statue' feature from the Dataframe
del client_0_bills['counter_statue']
client_0_bills.head()

,client_id,invoice_date,tarif_type,counter_number,counter_code,reading_remarque,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number,counter_type
0,train_Client_0,2014-03-24,11,1335667.0,203,8.0,1,82,0,0,0,14302,14384,4,0
1,train_Client_0,2013-03-29,11,1335667.0,203,6.0,1,1200,184,0,0,12294,13678,4,0
2,train_Client_0,2015-03-23,11,1335667.0,203,8.0,1,123,0,0,0,14624,14747,4,0
3,train_Client_0,2015-07-13,11,1335667.0,207,8.0,1,102,0,0,0,14747,14849,4,0
4,train_Client_0,2016-11-17,11,1335667.0,207,9.0,1,572,0,0,0,15066,15638,12,0